<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = $this->getQuestions();

        foreach ($questions as $q) {
            Question::firstOrCreate(
                ['question_text' => $q['question_text']],
                $q
            );
        }
    }

    private function getQuestions(): array
    {
        return [
            // General Knowledge (Easy)
            ['question_text' => 'What is the capital of France?', 'choice_a' => 'London', 'choice_b' => 'Berlin', 'choice_c' => 'Paris', 'choice_d' => 'Madrid', 'correct_choice' => 'C', 'explanation' => 'Paris is the capital and most populous city of France.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'How many continents are there on Earth?', 'choice_a' => '5', 'choice_b' => '6', 'choice_c' => '7', 'choice_d' => '8', 'correct_choice' => 'C', 'explanation' => 'There are 7 continents: Africa, Antarctica, Asia, Australia/Oceania, Europe, North America, and South America.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What is the largest planet in our solar system?', 'choice_a' => 'Saturn', 'choice_b' => 'Jupiter', 'choice_c' => 'Neptune', 'choice_d' => 'Uranus', 'correct_choice' => 'B', 'explanation' => 'Jupiter is the largest planet in our solar system.', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'What is the chemical symbol for water?', 'choice_a' => 'WA', 'choice_b' => 'H2O', 'choice_c' => 'HO2', 'choice_d' => 'O2H', 'correct_choice' => 'B', 'explanation' => 'Water is composed of two hydrogen atoms and one oxygen atom (H2O).', 'difficulty' => 'easy', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'What is 15% of 200?', 'choice_a' => '25', 'choice_b' => '35', 'choice_c' => '30', 'choice_d' => '20', 'correct_choice' => 'C', 'explanation' => '15% of 200 = (15/100) × 200 = 30.', 'difficulty' => 'easy', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'Who wrote "Romeo and Juliet"?', 'choice_a' => 'Charles Dickens', 'choice_b' => 'Jane Austen', 'choice_c' => 'William Shakespeare', 'choice_d' => 'Mark Twain', 'correct_choice' => 'C', 'explanation' => 'Romeo and Juliet was written by William Shakespeare around 1594–1596.', 'difficulty' => 'easy', 'category' => 'Literature', 'is_active' => true],
            ['question_text' => 'What is the speed of light approximately?', 'choice_a' => '300,000 km/s', 'choice_b' => '150,000 km/s', 'choice_c' => '500,000 km/s', 'choice_d' => '100,000 km/s', 'correct_choice' => 'A', 'explanation' => 'The speed of light in a vacuum is approximately 299,792,458 meters per second, roughly 300,000 km/s.', 'difficulty' => 'easy', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'What year did World War II end?', 'choice_a' => '1943', 'choice_b' => '1944', 'choice_c' => '1946', 'choice_d' => '1945', 'correct_choice' => 'D', 'explanation' => 'World War II ended in 1945 with Germany surrendering in May and Japan in September.', 'difficulty' => 'easy', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'What is the longest river in the world?', 'choice_a' => 'Amazon', 'choice_b' => 'Mississippi', 'choice_c' => 'Nile', 'choice_d' => 'Yangtze', 'correct_choice' => 'C', 'explanation' => 'The Nile River in Africa is generally considered the longest river in the world at about 6,650 km.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What is the smallest prime number?', 'choice_a' => '1', 'choice_b' => '2', 'choice_c' => '3', 'choice_d' => '0', 'correct_choice' => 'B', 'explanation' => '2 is the smallest and only even prime number.', 'difficulty' => 'easy', 'category' => 'Mathematics', 'is_active' => true],

            // Science (Medium)
            ['question_text' => 'What is the powerhouse of the cell?', 'choice_a' => 'Nucleus', 'choice_b' => 'Ribosome', 'choice_c' => 'Mitochondria', 'choice_d' => 'Golgi body', 'correct_choice' => 'C', 'explanation' => 'Mitochondria produce ATP through cellular respiration, earning them the nickname "powerhouse of the cell".', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What is the atomic number of carbon?', 'choice_a' => '8', 'choice_b' => '14', 'choice_c' => '6', 'choice_d' => '12', 'correct_choice' => 'C', 'explanation' => 'Carbon has atomic number 6, meaning it has 6 protons in its nucleus.', 'difficulty' => 'medium', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'Which gas do plants absorb during photosynthesis?', 'choice_a' => 'Oxygen', 'choice_b' => 'Nitrogen', 'choice_c' => 'Carbon Dioxide', 'choice_d' => 'Hydrogen', 'correct_choice' => 'C', 'explanation' => 'Plants absorb carbon dioxide (CO2) during photosynthesis to produce glucose and oxygen.', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What is Newton\'s second law of motion?', 'choice_a' => 'F = mv', 'choice_b' => 'F = ma', 'choice_c' => 'F = m/a', 'choice_d' => 'F = m²a', 'correct_choice' => 'B', 'explanation' => 'Newton\'s second law states that Force equals mass times acceleration (F = ma).', 'difficulty' => 'medium', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'What is the pH of a neutral solution?', 'choice_a' => '0', 'choice_b' => '14', 'choice_c' => '7', 'choice_d' => '5', 'correct_choice' => 'C', 'explanation' => 'A neutral solution has a pH of 7. Below 7 is acidic, above 7 is basic/alkaline.', 'difficulty' => 'medium', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'How many bones are in the adult human body?', 'choice_a' => '206', 'choice_b' => '196', 'choice_c' => '215', 'choice_d' => '230', 'correct_choice' => 'A', 'explanation' => 'The adult human body has 206 bones. Babies are born with about 270-300 bones that fuse over time.', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What does DNA stand for?', 'choice_a' => 'Deoxyribonucleic Acid', 'choice_b' => 'Deoxyribonitrogen Acid', 'choice_c' => 'Diribonucleic Acid', 'choice_d' => 'Deoxyribose Nucleic Acid', 'correct_choice' => 'A', 'explanation' => 'DNA stands for Deoxyribonucleic Acid, the molecule that carries genetic information.', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What is the chemical formula for table salt?', 'choice_a' => 'KCl', 'choice_b' => 'NaCl', 'choice_c' => 'CaCl2', 'choice_d' => 'MgCl2', 'correct_choice' => 'B', 'explanation' => 'Table salt is sodium chloride with the chemical formula NaCl.', 'difficulty' => 'medium', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'What is the speed of sound in air at 20°C?', 'choice_a' => '300 m/s', 'choice_b' => '440 m/s', 'choice_c' => '343 m/s', 'choice_d' => '250 m/s', 'correct_choice' => 'C', 'explanation' => 'The speed of sound in air at 20°C is approximately 343 meters per second.', 'difficulty' => 'medium', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'Which organ produces insulin?', 'choice_a' => 'Liver', 'choice_b' => 'Kidneys', 'choice_c' => 'Pancreas', 'choice_d' => 'Spleen', 'correct_choice' => 'C', 'explanation' => 'The pancreas produces insulin, a hormone that regulates blood sugar levels.', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],

            // Math (Medium)
            ['question_text' => 'What is the value of π (pi) to 2 decimal places?', 'choice_a' => '3.41', 'choice_b' => '3.14', 'choice_c' => '3.12', 'choice_d' => '3.16', 'correct_choice' => 'B', 'explanation' => 'Pi (π) is approximately 3.14159..., so to 2 decimal places it is 3.14.', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is the square root of 144?', 'choice_a' => '14', 'choice_b' => '11', 'choice_c' => '13', 'choice_d' => '12', 'correct_choice' => 'D', 'explanation' => '12 × 12 = 144, so the square root of 144 is 12.', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'If x + 5 = 12, what is x?', 'choice_a' => '5', 'choice_b' => '8', 'choice_c' => '7', 'choice_d' => '17', 'correct_choice' => 'C', 'explanation' => 'x = 12 - 5 = 7.', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is the sum of angles in a triangle?', 'choice_a' => '360°', 'choice_b' => '90°', 'choice_c' => '270°', 'choice_d' => '180°', 'correct_choice' => 'D', 'explanation' => 'The sum of interior angles in any triangle is always 180 degrees.', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is 2 to the power of 10?', 'choice_a' => '512', 'choice_b' => '2048', 'choice_c' => '1024', 'choice_d' => '256', 'correct_choice' => 'C', 'explanation' => '2^10 = 1024.', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'How many sides does a hexagon have?', 'choice_a' => '5', 'choice_b' => '6', 'choice_c' => '7', 'choice_d' => '8', 'correct_choice' => 'B', 'explanation' => 'A hexagon is a polygon with 6 sides and 6 angles.', 'difficulty' => 'easy', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is the area of a circle with radius 5? (Use π = 3.14)', 'choice_a' => '78.5', 'choice_b' => '31.4', 'choice_c' => '62.8', 'choice_d' => '15.7', 'correct_choice' => 'A', 'explanation' => 'Area = πr² = 3.14 × 5² = 3.14 × 25 = 78.5.', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is the next number in the sequence: 2, 4, 8, 16, ...?', 'choice_a' => '18', 'choice_b' => '24', 'choice_c' => '32', 'choice_d' => '20', 'correct_choice' => 'C', 'explanation' => 'Each number doubles: 2, 4, 8, 16, 32 (multiplied by 2).', 'difficulty' => 'easy', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is the greatest common divisor of 48 and 18?', 'choice_a' => '9', 'choice_b' => '3', 'choice_c' => '6', 'choice_d' => '12', 'correct_choice' => 'C', 'explanation' => 'GCD(48, 18) = 6. Factors of 48: 1,2,3,4,6,8,12,16,24,48. Factors of 18: 1,2,3,6,9,18. Greatest common = 6.', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is 25% of 80?', 'choice_a' => '15', 'choice_b' => '25', 'choice_c' => '20', 'choice_d' => '30', 'correct_choice' => 'C', 'explanation' => '25% of 80 = 0.25 × 80 = 20.', 'difficulty' => 'easy', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What type of triangle has all equal sides?', 'choice_a' => 'Isosceles', 'choice_b' => 'Scalene', 'choice_c' => 'Right', 'choice_d' => 'Equilateral', 'correct_choice' => 'D', 'explanation' => 'An equilateral triangle has all three sides equal in length.', 'difficulty' => 'easy', 'category' => 'Mathematics', 'is_active' => true],

            // Technology (Medium/Hard)
            ['question_text' => 'What does HTML stand for?', 'choice_a' => 'HyperText Markup Language', 'choice_b' => 'High Transfer Markup Language', 'choice_c' => 'HyperText Machine Language', 'choice_d' => 'Hyperlink Text Management Language', 'correct_choice' => 'A', 'explanation' => 'HTML stands for HyperText Markup Language, the standard language for creating web pages.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What does CPU stand for?', 'choice_a' => 'Central Processing Unit', 'choice_b' => 'Computer Processing Unit', 'choice_c' => 'Core Processor Utility', 'choice_d' => 'Central Program Unit', 'correct_choice' => 'A', 'explanation' => 'CPU stands for Central Processing Unit, the primary component of a computer that performs calculations.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What is the binary representation of the decimal number 10?', 'choice_a' => '1100', 'choice_b' => '1001', 'choice_c' => '1010', 'choice_d' => '1100', 'correct_choice' => 'C', 'explanation' => '10 in binary is 1010 (8+2 = 10).', 'difficulty' => 'medium', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What does HTTP stand for?', 'choice_a' => 'Hypertext Transfer Protocol', 'choice_b' => 'Hypertext Transport Protocol', 'choice_c' => 'High Transfer Text Protocol', 'choice_d' => 'Hyperlink Transfer Protocol', 'correct_choice' => 'A', 'explanation' => 'HTTP stands for Hypertext Transfer Protocol, the foundation for data communication on the World Wide Web.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What programming language uses the JVM (Java Virtual Machine)?', 'choice_a' => 'Python', 'choice_b' => 'C++', 'choice_c' => 'Java', 'choice_d' => 'Ruby', 'correct_choice' => 'C', 'explanation' => 'Java runs on the Java Virtual Machine (JVM), which allows Java programs to run on any platform.', 'difficulty' => 'medium', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What does SQL stand for?', 'choice_a' => 'Structured Query Language', 'choice_b' => 'Standard Query Language', 'choice_c' => 'System Query Language', 'choice_d' => 'Sequential Query Language', 'correct_choice' => 'A', 'explanation' => 'SQL stands for Structured Query Language, used to manage and query relational databases.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What does RAM stand for?', 'choice_a' => 'Random Access Memory', 'choice_b' => 'Read Access Memory', 'choice_c' => 'Rapid Access Memory', 'choice_d' => 'Readable Access Module', 'correct_choice' => 'A', 'explanation' => 'RAM stands for Random Access Memory, the computer\'s short-term memory used for running programs.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'Which company developed the Android operating system?', 'choice_a' => 'Apple', 'choice_b' => 'Microsoft', 'choice_c' => 'Google', 'choice_d' => 'Samsung', 'correct_choice' => 'C', 'explanation' => 'Android was developed by Android Inc. and then acquired by Google in 2005.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What is the maximum value of a signed 8-bit integer?', 'choice_a' => '127', 'choice_b' => '255', 'choice_c' => '128', 'choice_d' => '256', 'correct_choice' => 'A', 'explanation' => 'A signed 8-bit integer ranges from -128 to 127. Maximum positive value is 127.', 'difficulty' => 'hard', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'In programming, what is a "variable"?', 'choice_a' => 'A fixed constant value', 'choice_b' => 'A named storage location for data', 'choice_c' => 'A function parameter', 'choice_d' => 'A type of loop', 'correct_choice' => 'B', 'explanation' => 'A variable is a named storage location in memory that holds a value which can change during program execution.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],

            // History
            ['question_text' => 'In which year did the French Revolution begin?', 'choice_a' => '1799', 'choice_b' => '1776', 'choice_c' => '1789', 'choice_d' => '1804', 'correct_choice' => 'C', 'explanation' => 'The French Revolution began in 1789 with the storming of the Bastille on July 14.', 'difficulty' => 'medium', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'Who was the first President of the United States?', 'choice_a' => 'Thomas Jefferson', 'choice_b' => 'John Adams', 'choice_c' => 'Benjamin Franklin', 'choice_d' => 'George Washington', 'correct_choice' => 'D', 'explanation' => 'George Washington served as the first President of the United States from 1789 to 1797.', 'difficulty' => 'easy', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'What ancient wonder was located in Alexandria, Egypt?', 'choice_a' => 'Colossus of Rhodes', 'choice_b' => 'Lighthouse of Alexandria', 'choice_c' => 'Hanging Gardens', 'choice_d' => 'Temple of Artemis', 'correct_choice' => 'B', 'explanation' => 'The Lighthouse of Alexandria was one of the Seven Wonders of the Ancient World, located in Alexandria, Egypt.', 'difficulty' => 'medium', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'Who was the first human to walk on the Moon?', 'choice_a' => 'Buzz Aldrin', 'choice_b' => 'Yuri Gagarin', 'choice_c' => 'Neil Armstrong', 'choice_d' => 'John Glenn', 'correct_choice' => 'C', 'explanation' => 'Neil Armstrong became the first human to walk on the Moon on July 20, 1969, during the Apollo 11 mission.', 'difficulty' => 'easy', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'What empire was ruled by Julius Caesar?', 'choice_a' => 'Greek Empire', 'choice_b' => 'Roman Empire', 'choice_c' => 'Byzantine Empire', 'choice_d' => 'Ottoman Empire', 'correct_choice' => 'B', 'explanation' => 'Julius Caesar was a Roman statesman and general who played a critical role in the Roman Empire.', 'difficulty' => 'easy', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'What was the name of the ship that sank in 1912 after hitting an iceberg?', 'choice_a' => 'Titanic', 'choice_b' => 'Lusitania', 'choice_c' => 'Britannic', 'choice_d' => 'Olympic', 'correct_choice' => 'A', 'explanation' => 'The RMS Titanic sank on April 15, 1912, after hitting an iceberg during its maiden voyage.', 'difficulty' => 'easy', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'When did the Berlin Wall fall?', 'choice_a' => '1987', 'choice_b' => '1991', 'choice_c' => '1993', 'choice_d' => '1989', 'correct_choice' => 'D', 'explanation' => 'The Berlin Wall fell on November 9, 1989, marking the end of the Cold War division in Germany.', 'difficulty' => 'medium', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'Which country was the first to give women the right to vote?', 'choice_a' => 'United Kingdom', 'choice_b' => 'New Zealand', 'choice_c' => 'United States', 'choice_d' => 'Australia', 'correct_choice' => 'B', 'explanation' => 'New Zealand was the first self-governing country to grant women the right to vote in 1893.', 'difficulty' => 'hard', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'Who painted the Mona Lisa?', 'choice_a' => 'Michelangelo', 'choice_b' => 'Raphael', 'choice_c' => 'Caravaggio', 'choice_d' => 'Leonardo da Vinci', 'correct_choice' => 'D', 'explanation' => 'The Mona Lisa was painted by Leonardo da Vinci between approximately 1503 and 1519.', 'difficulty' => 'easy', 'category' => 'History', 'is_active' => true],
            ['question_text' => 'Which empire was the largest in history by area?', 'choice_a' => 'Roman Empire', 'choice_b' => 'Mongol Empire', 'choice_c' => 'British Empire', 'choice_d' => 'Ottoman Empire', 'correct_choice' => 'C', 'explanation' => 'The British Empire was the largest empire in history, covering about 24% of the Earth\'s total land area at its peak.', 'difficulty' => 'hard', 'category' => 'History', 'is_active' => true],

            // Geography
            ['question_text' => 'What is the largest country in the world by area?', 'choice_a' => 'Canada', 'choice_b' => 'China', 'choice_c' => 'USA', 'choice_d' => 'Russia', 'correct_choice' => 'D', 'explanation' => 'Russia is the largest country in the world, covering about 17.1 million square kilometers.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What is the capital of Australia?', 'choice_a' => 'Sydney', 'choice_b' => 'Melbourne', 'choice_c' => 'Canberra', 'choice_d' => 'Brisbane', 'correct_choice' => 'C', 'explanation' => 'Canberra is the capital city of Australia, chosen as a compromise between Sydney and Melbourne.', 'difficulty' => 'medium', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'Which is the highest mountain in the world?', 'choice_a' => 'K2', 'choice_b' => 'Kangchenjunga', 'choice_c' => 'Lhotse', 'choice_d' => 'Mount Everest', 'correct_choice' => 'D', 'explanation' => 'Mount Everest is the highest mountain above sea level at 8,848.86 meters.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What is the smallest country in the world?', 'choice_a' => 'Monaco', 'choice_b' => 'San Marino', 'choice_c' => 'Vatican City', 'choice_d' => 'Liechtenstein', 'correct_choice' => 'C', 'explanation' => 'Vatican City is the world\'s smallest country by area, covering approximately 0.44 km².', 'difficulty' => 'medium', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'Through which country does the Amazon River primarily flow?', 'choice_a' => 'Argentina', 'choice_b' => 'Peru', 'choice_c' => 'Colombia', 'choice_d' => 'Brazil', 'correct_choice' => 'D', 'explanation' => 'The Amazon River flows primarily through Brazil, with its mouth at the Atlantic Ocean.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What is the capital of Japan?', 'choice_a' => 'Osaka', 'choice_b' => 'Kyoto', 'choice_c' => 'Tokyo', 'choice_d' => 'Hiroshima', 'correct_choice' => 'C', 'explanation' => 'Tokyo is the capital and largest city of Japan.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'How many countries are in Africa?', 'choice_a' => '48', 'choice_b' => '54', 'choice_c' => '58', 'choice_d' => '51', 'correct_choice' => 'B', 'explanation' => 'Africa has 54 recognized sovereign countries, making it the continent with the most countries.', 'difficulty' => 'hard', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What is the largest ocean on Earth?', 'choice_a' => 'Atlantic Ocean', 'choice_b' => 'Indian Ocean', 'choice_c' => 'Southern Ocean', 'choice_d' => 'Pacific Ocean', 'correct_choice' => 'D', 'explanation' => 'The Pacific Ocean is the largest ocean, covering about 165 million square kilometers.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What river flows through Egypt?', 'choice_a' => 'Congo', 'choice_b' => 'Zambezi', 'choice_c' => 'Niger', 'choice_d' => 'Nile', 'correct_choice' => 'D', 'explanation' => 'The Nile River flows through Egypt from south to north, emptying into the Mediterranean Sea.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'Which desert is the largest in the world?', 'choice_a' => 'Gobi Desert', 'choice_b' => 'Sahara Desert', 'choice_c' => 'Arabian Desert', 'choice_d' => 'Antarctic Desert', 'correct_choice' => 'D', 'explanation' => 'The Antarctic Desert is the largest desert in the world. The Sahara is the largest hot desert.', 'difficulty' => 'hard', 'category' => 'Geography', 'is_active' => true],

            // Language & Literature
            ['question_text' => 'What is the most widely spoken language in the world by native speakers?', 'choice_a' => 'English', 'choice_b' => 'Mandarin Chinese', 'choice_c' => 'Spanish', 'choice_d' => 'Hindi', 'correct_choice' => 'B', 'explanation' => 'Mandarin Chinese has the most native speakers with over 900 million people.', 'difficulty' => 'medium', 'category' => 'Language', 'is_active' => true],
            ['question_text' => 'What is a synonym for "happy"?', 'choice_a' => 'Sad', 'choice_b' => 'Joyful', 'choice_c' => 'Angry', 'choice_d' => 'Tired', 'correct_choice' => 'B', 'explanation' => 'Joyful is a synonym for happy, both meaning a feeling of great pleasure or contentment.', 'difficulty' => 'easy', 'category' => 'Language', 'is_active' => true],
            ['question_text' => 'Who wrote "1984"?', 'choice_a' => 'Aldous Huxley', 'choice_b' => 'H.G. Wells', 'choice_c' => 'George Orwell', 'choice_d' => 'Ray Bradbury', 'correct_choice' => 'C', 'explanation' => '1984 (Nineteen Eighty-Four) was written by George Orwell, published in 1949.', 'difficulty' => 'medium', 'category' => 'Literature', 'is_active' => true],
            ['question_text' => 'Which planet is known as the "Blue Planet"?', 'choice_a' => 'Neptune', 'choice_b' => 'Uranus', 'choice_c' => 'Saturn', 'choice_d' => 'Earth', 'correct_choice' => 'D', 'explanation' => 'Earth is called the "Blue Planet" because of the blue color of its oceans seen from space.', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'What is the study of earthquakes called?', 'choice_a' => 'Volcanology', 'choice_b' => 'Meteorology', 'choice_c' => 'Geology', 'choice_d' => 'Seismology', 'correct_choice' => 'D', 'explanation' => 'Seismology is the study of earthquakes and the propagation of elastic waves through the Earth.', 'difficulty' => 'medium', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'What is the hardest natural substance on Earth?', 'choice_a' => 'Quartz', 'choice_b' => 'Diamond', 'choice_c' => 'Granite', 'choice_d' => 'Platinum', 'correct_choice' => 'B', 'explanation' => 'Diamond is the hardest natural substance on Earth, rating 10 on the Mohs hardness scale.', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'What element has the chemical symbol "Fe"?', 'choice_a' => 'Fluorine', 'choice_b' => 'Iron', 'choice_c' => 'Copper', 'choice_d' => 'Ferrum', 'correct_choice' => 'B', 'explanation' => 'Fe is the chemical symbol for Iron, derived from the Latin word "Ferrum".', 'difficulty' => 'medium', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'How many colors are in a rainbow?', 'choice_a' => '6', 'choice_b' => '8', 'choice_c' => '5', 'choice_d' => '7', 'correct_choice' => 'D', 'explanation' => 'A rainbow has 7 colors: red, orange, yellow, green, blue, indigo, and violet (ROY G BIV).', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'What is the largest organ in the human body?', 'choice_a' => 'Brain', 'choice_b' => 'Liver', 'choice_c' => 'Lungs', 'choice_d' => 'Skin', 'correct_choice' => 'D', 'explanation' => 'The skin is the largest organ in the human body, making up about 16% of body weight.', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What does "WWW" stand for in a web address?', 'choice_a' => 'World Wide Web', 'choice_b' => 'Web World Wide', 'choice_c' => 'Worldwide Weblink', 'choice_d' => 'Wide World Web', 'correct_choice' => 'A', 'explanation' => 'WWW stands for World Wide Web, the information space where web resources are identified by URLs.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],

            // Hard questions
            ['question_text' => 'What is the Heisenberg Uncertainty Principle?', 'choice_a' => 'Energy cannot be created or destroyed', 'choice_b' => 'Mass and energy are equivalent', 'choice_c' => 'You cannot simultaneously know exact position and momentum of a particle', 'choice_d' => 'Every action has an equal and opposite reaction', 'correct_choice' => 'C', 'explanation' => 'Heisenberg\'s Uncertainty Principle states you cannot precisely measure both position and momentum of a quantum particle simultaneously.', 'difficulty' => 'hard', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'What is the Fibonacci sequence starting with 1, 1?', 'choice_a' => '1, 1, 2, 3, 5, 8, 13...', 'choice_b' => '1, 1, 2, 4, 6, 10, 16...', 'choice_c' => '1, 1, 3, 5, 7, 11, 13...', 'choice_d' => '1, 1, 2, 3, 7, 11, 18...', 'correct_choice' => 'A', 'explanation' => 'The Fibonacci sequence: each number is the sum of the two preceding ones: 1, 1, 2, 3, 5, 8, 13, 21...', 'difficulty' => 'medium', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'Which gas is most abundant in Earth\'s atmosphere?', 'choice_a' => 'Oxygen', 'choice_b' => 'Carbon Dioxide', 'choice_c' => 'Nitrogen', 'choice_d' => 'Argon', 'correct_choice' => 'C', 'explanation' => 'Nitrogen makes up about 78% of Earth\'s atmosphere. Oxygen is about 21%.', 'difficulty' => 'medium', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'What is the term for a word that reads the same backwards and forwards?', 'choice_a' => 'Anagram', 'choice_b' => 'Oxymoron', 'choice_c' => 'Palindrome', 'choice_d' => 'Homonym', 'correct_choice' => 'C', 'explanation' => 'A palindrome reads the same forwards and backwards, like "racecar" or "level".', 'difficulty' => 'medium', 'category' => 'Language', 'is_active' => true],
            ['question_text' => 'What is the half-life of Carbon-14?', 'choice_a' => '1,430 years', 'choice_b' => '5,730 years', 'choice_c' => '10,000 years', 'choice_d' => '3,500 years', 'correct_choice' => 'B', 'explanation' => 'Carbon-14 has a half-life of approximately 5,730 years, used in radiocarbon dating.', 'difficulty' => 'hard', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'What is the process by which plants make food using sunlight?', 'choice_a' => 'Respiration', 'choice_b' => 'Transpiration', 'choice_c' => 'Fermentation', 'choice_d' => 'Photosynthesis', 'correct_choice' => 'D', 'explanation' => 'Photosynthesis is the process by which plants use sunlight, water, and CO2 to produce glucose and oxygen.', 'difficulty' => 'easy', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What is the boiling point of water at sea level in Celsius?', 'choice_a' => '90°C', 'choice_b' => '120°C', 'choice_c' => '100°C', 'choice_d' => '80°C', 'correct_choice' => 'C', 'explanation' => 'Water boils at 100°C (212°F) at standard atmospheric pressure (sea level).', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'Who proposed the theory of general relativity?', 'choice_a' => 'Isaac Newton', 'choice_b' => 'Niels Bohr', 'choice_c' => 'Max Planck', 'choice_d' => 'Albert Einstein', 'correct_choice' => 'D', 'explanation' => 'Albert Einstein proposed the theory of general relativity in 1915.', 'difficulty' => 'easy', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'What is the chemical symbol for gold?', 'choice_a' => 'Gd', 'choice_b' => 'Au', 'choice_c' => 'Go', 'choice_d' => 'Ag', 'correct_choice' => 'B', 'explanation' => 'Au is the chemical symbol for gold, derived from the Latin word "Aurum".', 'difficulty' => 'medium', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'What is the SI unit of electric current?', 'choice_a' => 'Volt', 'choice_b' => 'Ohm', 'choice_c' => 'Watt', 'choice_d' => 'Ampere', 'correct_choice' => 'D', 'explanation' => 'The Ampere (A) is the SI unit of electric current, named after André-Marie Ampère.', 'difficulty' => 'medium', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'How many chambers does the human heart have?', 'choice_a' => '2', 'choice_b' => '4', 'choice_c' => '3', 'choice_d' => '6', 'correct_choice' => 'B', 'explanation' => 'The human heart has 4 chambers: right atrium, right ventricle, left atrium, and left ventricle.', 'difficulty' => 'easy', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What is the most common blood type?', 'choice_a' => 'B+', 'choice_b' => 'AB+', 'choice_c' => 'A+', 'choice_d' => 'O+', 'correct_choice' => 'D', 'explanation' => 'O+ (O positive) is the most common blood type worldwide.', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What type of energy does the sun primarily produce?', 'choice_a' => 'Chemical energy', 'choice_b' => 'Nuclear fusion energy', 'choice_c' => 'Nuclear fission energy', 'choice_d' => 'Gravitational energy', 'correct_choice' => 'B', 'explanation' => 'The Sun produces energy through nuclear fusion, combining hydrogen atoms to form helium.', 'difficulty' => 'medium', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'What is the name of the force that keeps planets in orbit?', 'choice_a' => 'Electromagnetic force', 'choice_b' => 'Strong nuclear force', 'choice_c' => 'Gravity', 'choice_d' => 'Centrifugal force', 'correct_choice' => 'C', 'explanation' => 'Gravity is the force that keeps planets in orbit around the sun.', 'difficulty' => 'easy', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'What is 0 factorial (0!)?', 'choice_a' => '0', 'choice_b' => 'Undefined', 'choice_c' => '1', 'choice_d' => '∞', 'correct_choice' => 'C', 'explanation' => 'By convention, 0! = 1. This is the empty product, the product of no numbers.', 'difficulty' => 'hard', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'What is the chemical formula for glucose?', 'choice_a' => 'C6H12O6', 'choice_b' => 'C12H22O11', 'choice_c' => 'C6H10O6', 'choice_d' => 'C6H6O6', 'correct_choice' => 'A', 'explanation' => 'Glucose has the molecular formula C6H12O6, a simple sugar used as an energy source.', 'difficulty' => 'hard', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'What does "AI" stand for in technology?', 'choice_a' => 'Automated Intelligence', 'choice_b' => 'Artificial Intelligence', 'choice_c' => 'Applied Intelligence', 'choice_d' => 'Advanced Interface', 'correct_choice' => 'B', 'explanation' => 'AI stands for Artificial Intelligence, the simulation of human intelligence processes by computer systems.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'What is the unit of measurement for frequency?', 'choice_a' => 'Newton', 'choice_b' => 'Hertz', 'choice_c' => 'Joule', 'choice_d' => 'Pascal', 'correct_choice' => 'B', 'explanation' => 'Hertz (Hz) is the SI unit of frequency, measuring cycles per second.', 'difficulty' => 'medium', 'category' => 'Physics', 'is_active' => true],
            ['question_text' => 'What is the process of a solid changing directly to gas called?', 'choice_a' => 'Evaporation', 'choice_b' => 'Condensation', 'choice_c' => 'Sublimation', 'choice_d' => 'Melting', 'correct_choice' => 'C', 'explanation' => 'Sublimation is the process where a solid changes directly into a gas without passing through the liquid state.', 'difficulty' => 'hard', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'How many planets are in our solar system?', 'choice_a' => '9', 'choice_b' => '8', 'choice_c' => '7', 'choice_d' => '10', 'correct_choice' => 'B', 'explanation' => 'Our solar system has 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Pluto was reclassified as a dwarf planet in 2006.', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],

            // Additional questions to reach 100
            ['question_text' => 'What is the freezing point of water in Fahrenheit?', 'choice_a' => '0°F', 'choice_b' => '32°F', 'choice_c' => '100°F', 'choice_d' => '212°F', 'correct_choice' => 'B', 'explanation' => 'Water freezes at 32°F (0°C) at standard atmospheric pressure.', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'Which blood type is the universal donor?', 'choice_a' => 'A-', 'choice_b' => 'AB-', 'choice_c' => 'O-', 'choice_d' => 'B-', 'correct_choice' => 'C', 'explanation' => 'O- (O negative) is the universal donor for red blood cells as it lacks A, B, and Rh antigens.', 'difficulty' => 'medium', 'category' => 'Biology', 'is_active' => true],
            ['question_text' => 'What is the largest continent by area?', 'choice_a' => 'Africa', 'choice_b' => 'North America', 'choice_c' => 'Asia', 'choice_d' => 'Europe', 'correct_choice' => 'C', 'explanation' => 'Asia is the largest continent covering about 44.6 million km², which is 30% of Earth\'s total land area.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What does "RAM" stand for?', 'choice_a' => 'Random Access Memory', 'choice_b' => 'Read Access Memory', 'choice_c' => 'Rapid Access Memory', 'choice_d' => 'Readable Application Memory', 'correct_choice' => 'A', 'explanation' => 'RAM stands for Random Access Memory, used by the computer for short-term data storage while running programs.', 'difficulty' => 'easy', 'category' => 'Technology', 'is_active' => true],
            ['question_text' => 'How many degrees are in a full circle?', 'choice_a' => '90', 'choice_b' => '180', 'choice_c' => '270', 'choice_d' => '360', 'correct_choice' => 'D', 'explanation' => 'A full circle contains 360 degrees, a convention dating back to ancient Babylonian mathematics.', 'difficulty' => 'easy', 'category' => 'Mathematics', 'is_active' => true],
            ['question_text' => 'Which planet is closest to the Sun?', 'choice_a' => 'Venus', 'choice_b' => 'Earth', 'choice_c' => 'Mars', 'choice_d' => 'Mercury', 'correct_choice' => 'D', 'explanation' => 'Mercury is the closest planet to the Sun, orbiting at an average distance of about 57.9 million km.', 'difficulty' => 'easy', 'category' => 'Science', 'is_active' => true],
            ['question_text' => 'What is the main language spoken in Brazil?', 'choice_a' => 'Spanish', 'choice_b' => 'French', 'choice_c' => 'Portuguese', 'choice_d' => 'English', 'correct_choice' => 'C', 'explanation' => 'Portuguese is the official language of Brazil, spoken by virtually the entire population.', 'difficulty' => 'easy', 'category' => 'Geography', 'is_active' => true],
            ['question_text' => 'What is the chemical formula for carbon dioxide?', 'choice_a' => 'CO', 'choice_b' => 'CO2', 'choice_c' => 'C2O', 'choice_d' => 'CO3', 'correct_choice' => 'B', 'explanation' => 'Carbon dioxide has one carbon atom bonded to two oxygen atoms, giving the formula CO2.', 'difficulty' => 'easy', 'category' => 'Chemistry', 'is_active' => true],
            ['question_text' => 'In which year did the first iPhone launch?', 'choice_a' => '2005', 'choice_b' => '2006', 'choice_c' => '2008', 'choice_d' => '2007', 'correct_choice' => 'D', 'explanation' => 'Apple\'s first iPhone was announced by Steve Jobs on January 9, 2007 and released on June 29, 2007.', 'difficulty' => 'medium', 'category' => 'Technology', 'is_active' => true],
        ];
    }
}
